---
- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: no


  vars:

  vars_files:
    - ../Creds/big_creds.yaml

  tasks:
  - name: Create a JAS3 DEC
    uri:
      url: https://18.133.146.189/mgmt/shared/appsvcs/declare
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: POST
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no


      
  
  


...